### ISSUE TITLE
[Labo 4] Corriger le corrigé du dimensionnement

### ISSUE THREAD

**Issue by parastuffs** [BEAMS-EE/ELECH301#18]
- Retirer les références au manque de temps pendant le labo
- Vérifier les circuits
- Changer le premier gm (0.155S)

**Comment by KenN7** [comment]
\usetikzlibrary{babel,positioning,calc} ?

**Comment by parastuffs** [comment]
Pas eu besoin de changer le \usetikzlibrary. Utiliser le .sty dans le dossier suffit et est plus simple.
