### ISSUE TITLE
[TP5] Erreur point de fonctionnement exercice 7

### ISSUE THREAD

**Issue by sunytux** [BEAMS-EE/ELECH301#2]

**Comment by parastuffs** [comment]
Quelle est l'erreur, au juste ?
C'est le fait qu'on ait choisi un RD de 173 Ohm pour déterminer le point de fonctionnement (12V, 69mA) et qu'on choisi ensuite RD = 200 Ohm pour le gain ?

**Comment by parastuffs** [comment]
Il faut en fait ajouter « gain à vide » dans l'énoncé pour que le calcul dans le corrigé soit correct.
